apiVersion: apps/v1
kind: Deployment
metadata:
  name: poller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poller
  template:
    metadata:
     labels:
       app: poller
    spec:
      containers:
      - name: poller
        image: sanixto/poller:1
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: poller-config
