apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  labels:
    name: {{ .Release.Name }}-{{ .Chart.Name }}-service
    {{ .Values.selector | toYaml }}
spec:
  type: ClusterIP
  selector:
    {{ .Values.selector | toYaml }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
