replicaCount: 1

selector:
  app: client

image:
  repository: sanixto
  name: client
  tag: 1

service:
  ports:
    - port: 80
      targetPort: 80
      containerPort: 80

ingress:
  path: /
  port: 80

virtual:
  timeout: 5s
  retries:
    attempts: 3
    retryOn: 5xx
    perTryTimeout: 5s  

trafficPolicy:
  consecutive5xxErrors: 7
  interval: 5m
  baseEjectionTime: 15m
  maxEjectionPercent: 80