replicaCount: 1

selector:
  app: user

image:
  name: user-service
  tag: latest

service:
  ports:
    - port: 8080
      targetPort: 8080
      containerPort: 8080

ingress:
  path: /user
  port: 8080

migrations:
  image:
    name: user-service-migrations
    tag: latest
  config:
    POSTGRESQL_URL: "postgres://user:user@postgres-service:5432/tokens?sslmode=disable"
    VERSION: "20211128095755"

configs:
  DB_DATABASE: "tokens"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"

secrets:
  DB_USERNAME: "dXNlcg==" #user
  DB_PASSWORD: "dXNlcg==" #user