replicaCount: 1

selector:
  app: token-manager

image:
  repository: sanixto
  name: token-manager
  tag: 1

service:
  ports:
    - port: 3000
      targetPort: 3000
      containerPort: 3000

ingress:
  path: /token
  port: 3000

migrations:
  image:
    repository: sanixto
    name: token-manager-migrations
    tag: 1
  config:
    POSTGRESQL_URL: "postgres://user:user@postgres:5432/tokens?sslmode=disable"
    VERSION: "20211128095755"

configs:
  DB_DATABASE: "tokens"
  DB_HOST: "postgres"
  DB_PORT: "5432"

secrets:
  DB_USERNAME: "dXNlcg==" #user
  DB_PASSWORD: "dXNlcg==" #user