apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ .Values.selector | toYaml }}
  template:
    metadata:
     labels:
       {{ .Values.selector | toYaml }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: "IfNotPresent"
          name: {{ .Values.image.name }}
          ports:
            {{- range .Values.service.ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}

