apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
spec:
  type: ClusterIP
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      containerPort: {{ .containerPort }}
    {{- end }}
  selector:
    {{ .Values.selector | toYaml }}
