replicaCount: 1

selector:
  app: client

image:
  repository: sanixto
  name: client
  tag: 1

service:
  ports:
    - port: 80
      targetPort: 80
      containerPort: 80

ingress:
  path: /
  port: 80
