apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ .Values.selector | toYaml }}
  template:
    metadata:
     labels:
       {{ .Values.selector | toYaml }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Never
        ports:
          {{- range .Values.service.ports }}
            - containerPort: {{ .containerPort }}
          {{- end }}
