replicaCount: 1

selector:
  app: token-manager

image:
  name: token-manager
  tag: latest

service:
  ports:
    - port: 3000
      targetPort: 3000
      containerPort: 3000

ingress:
  path: /token
  port: 3000

migrations:
  image:
    name: token-manager-migrations
    tag: latest
  config:
    POSTGRESQL_URL: "postgres://user:user@postgres:5432/tokens?sslmode=disable"
    VERSION: "20211128095755"

configs:
  DB_DATABASE: "tokens"
  DB_HOST: "postgres"
  DB_PORT: "5432"

secrets:
  DB_USERNAME: "dXNlcg==" #user
  DB_PASSWORD: "dXNlcg==" #user

virtual:
  timeout: 5s
  retries:
    attempts: 3
    retryOn: 5xx
    perTryTimeout: 5s  

trafficPolicy:
  consecutive5xxErrors: 7
  interval: 5m
  baseEjectionTime: 15m
  maxEjectionPercent: 80