apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-destination
spec:
  host: {{ .Release.Name }}-{{ .Chart.Name }}-service
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: {{ .Values.trafficPolicy.consecutive5xxErrors }}
      interval: {{ .Values.trafficPolicy.interval }}
      baseEjectionTime: {{ .Values.trafficPolicy.baseEjectionTime }}
      maxEjectionPercent: {{ .Values.trafficPolicy.maxEjectionPercent }}