apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    name: user-deployment
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-pod
      app: user
  template:
    metadata:
      name: user-pod
      labels:
        name: user-pod
        app: user
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user-config
            - secretRef:
                name: user-secret 
      initContainers:
        - name: run-migrations
          image: user-service-migrations:latest
          imagePullPolicy: Never
          command: ["migrate", "-path", "/migrations", "-database", "$(POSTGRESQL_URL)", "goto", "$(VERSION)"]
          env:
            - name: POSTGRESQL_URL
              value: "postgres://postgres:postgres@postgres-service:5432/tokens?sslmode=disable"
            - name: VERSION
              value: "1680253200"