apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-factory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token-factory
  template:
    metadata:
     labels:
       app: token-factory
    spec:
      containers:
      - name: token-factory
        image: sanixto/token-factory:1
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: token-factory-config